### PR TITLE
ECO-134-amend: flash when orderbook updated

### PR DESCRIPTION
**Pull request by chiumax**
redo of #276 
https://streamable.com/ktd9i7
looks like whenever orderbook updates TV chart gets rerendered -- not good?

testing:
update levels manually
```ts
  useEffect(() => {
    setTimeout(() => {
      queryClient.setQueryData(
        ["orderbook", marketData?.market_id],
        (oldData: Orderbook | undefined) => {
          if (oldData) {
            const newData: Orderbook = {
              bids: [...oldData.bids],
              asks: [...oldData.asks],
              updatedLevel: {
                price: oldData.bids[0].price,
                size: 10000,
              },
            };
            newData.bids[0] = { ...newData.bids[0], size: 10000 };
            console.log(newData);
            return newData;
          }
          return oldData;
        },
      );
    }, 5000);
    setTimeout(() => {
      queryClient.setQueryData(
        ["orderbook", marketData?.market_id],
        (oldData: Orderbook | undefined) => {
          if (oldData) {
            const newData: Orderbook = {
              bids: [...oldData.bids],
              asks: [...oldData.asks],
              updatedLevel: {
                price: oldData.bids[1].price,
                size: 30000,
              },
            };
            newData.bids[1] = { ...newData.bids[1], size: 30000 };
            console.log(newData);
            return newData;
          }
          return oldData;
        },
      );
    }, 5250);
    setTimeout(() => {
      queryClient.setQueryData(
        ["orderbook", marketData?.market_id],
        (oldData: Orderbook | undefined) => {
          if (oldData) {
            const newData: Orderbook = {
              bids: [...oldData.bids],
              asks: [...oldData.asks],
              updatedLevel: {
                price: oldData.bids[0].price,
                size: 10000,
              },
            };
            newData.bids[0] = { ...newData.bids[0], size: 10000 };
            console.log(newData);
            return newData;
          }
          return oldData;
        },
      );
    }, 5100);
    setTimeout(() => {
      queryClient.setQueryData(
        ["orderbook", marketData?.market_id],
        (oldData: Orderbook | undefined) => {
          if (oldData) {
            const newData: Orderbook = {
              bids: [...oldData.bids],
              asks: [...oldData.asks],
              updatedLevel: {
                price: oldData.bids[1].price,
                size: 300000,
              },
            };
            newData.bids[1] = { ...newData.bids[1], size: 30000 };
            console.log(newData);
            return newData;
          }
          return oldData;
        },
      );
    }, 5150);
  }, [marketData?.market_id, queryClient]);
```

### CODE REVIEW

**Review by bogberry — CHANGES_REQUESTED** [review]
It looks like the green/red background indicating the size of the price level disappears after displaying the flash?

**Comment by bogberry** [comment]
Also I think we need to account for the fact that you get multiple updates in under 100ms.

**Comment by chiumax** [comment]
> Also I think we need to account for the fact that you get multiple updates in under 100ms.

did you test with customized use effects, i think it works appropriately for updates under 100ms, it looks like it just resets the animation. i can try to attach a gif later

**Comment by chiumax** [comment]
> It looks like the green/red background indicating the size of the price level disappears after displaying the flash?

just verified this isn't an issue, the stuff i copy pasted here is too small so it looks like it disappears, I've updated the snippet

**Comment by bogberry** [comment]
Yeah I think these were issues with the testing I was doing. Disregard my previous comments, these seem fine

**Comment by bogberry** [comment]
but the orderbook updates causing a tradingview refresh is a problem—I can't figure out why this is happening at the moment. I'll try debugging some more next week and see if I can get to the bottom of this

**Pull request merged**
