### PR TITLE
Eco 133: add sorting to orders table

### PR DESCRIPTION
**Pull request by chiumax**
better styling for sorting indicator?
also, which columns should have sorting?

### CODE REVIEW

**Comment by chiumax** [comment]
yea i agree, this still needs some work, making it a draft again

**Comment by bogberry** [comment]
- I agree with @BriungRi, the column headers should be `cursor: pointer` and the text should not be highlighted.
- Probably should make it possible for the user to sort on every column.
- The sort icons should be more prominent. Discuss with @xorkiki?
- As @BriungRi mentioned, sorting by a column should not cause a layout shift.

**Comment by bogberry** [comment]
I've made this into a draft

**Comment by chiumax** [comment]
closing in favor of: https://github.com/econia-labs/econia/pull/378

**Pull request closed without merging**
